os: linux
arch: arm64-graviton2

sudo: required
services:
  - docker

addons:
  apt:
    update: true

env:
  global:
    - secure: LevFH7UVZoGu+6SPPAU9J7BLbfPeDkf8bsqSHnVGGcwOZN4Z8NH8QQvCeFa/ceULYjd1HQqlRcE5FO6et+BfK/aeXhCb8gjFYO/HblYFhzUddVrtqVVlA6H+q59+B9SddbFXH0wZ3B8KZ63oCRpjDJB4Fln0zwLbQYLpRCCB3jgE40jQtkA/uuYIYlKypbz+mMNFNY4ntOImFz1cSv9PMtOXFknbWz+OR4sQMSt3qtMvllFg+4/gEL5h377lbk3C4g7aomM62y/cCGKfS3EKJzzaT0fhOcxXBPWhBqR6leL2u418oMjMlOgCgYYAtCqqzyZzJQ3pl7RUxhxkaaedPSv0gQxZMTVvKjJgrsiWF+0ORWKLIP/RzImuRSVjlh44T5NyH0fuVN13XbSBDAphnM06p/ck8rfEOnPHjRAQsH00/J0bRCWHlsW2+c2TixpXyR6zso2uT5Cavi3z0KH3jZwaDVRg6Evj2OBSH1cYIV/97XKxF2bw4IDkPO/RsWhKaFpFS+3yjnOxYqmuSZCP8/nHzYDUwcFiA6t558jHT3/XxVMurqZGJXhfA+X4ohyHtO2zqAlEXwrYfvHDPbWjsiEKkl4ERnF4Exzb7vcSzdFGg3tEz98D+03qTNpvPwqmuzzDlsDKo3wROTHiKLWSQyR1ToxoxX0pQ3iGY2zaO8o=
    - secure: jZkPSTR85dZjuCUehptreSGOImPX59+qZspGt27e33N8GuIJ07kLIt/xD0BO5VtCNiBIJZsY3R0Z58gmgRZXMouZwYzaGihhwQqmIVhLkeF3I2mjVqDCzU4bqUwfod/AvqiZ9zOz+ASwL7M8vR3N3IDVS20oVza8hXztbfpI9qa/2xoG3w5nF6MT1JEhfXHiertU8F9uhvsNM6UQod54X6lPLrYB1HNg6PAst7rWh0aBdnQHurmIyxhRgMtOwEXSi/BEZfsEGujUE0Czp04cevuSUteGhcV45EF78tBAPThKj3JxAmnXJUhMvuBefq+/cfrHGEK+hl9cSldnKUJCVEk6q5Pn4XKWYo85mHtr8jR/QxyyzepE9GAvdnFm4g78ULyLdA2cn0bw8Wa4J1Khrq/KcxW5qXd6Z6FovfKW5Bv5cXA66xndw77FG0lNyGtilnHeY1w4Gquw1+be/7qU+I5RbWa5HFX8M3rYZVb5bEqWcVEIHFVs6CZr/STLyuRrgtstyAmQTqzcPLsqwXFrBrNUwBnLyP5AgOLz7ZyEGn2Rnf40MU5KvF8tBqm2cCDQqnn8eosTEbKSmVfKGJ8woDcSCAh5Xk+Fk34m075o9w9V0dKIex6lrqB0eGBHdUWv0jtRhbFHGOwacZW1qlhCW6eDzgCrSr2yr5MM5gynGHQ=

before_install:
  - cd jenkins
  - make jocker

before_script:
  - cd ..
  - make pull-base

script:
  - make build

after_success:
  - make jocker-ready
  - make agents
  - make test || travis_terminate 1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
    --password-stdin
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    make release; fi
