sudo: required
env:
  global:
    - secure: 61VMPNg0e4SjVCuHR2Agvx43J9PzqDZHKspkCyU4ml+ypB1XjW8M8FM00v8COg/AfJUzWx25irsaRoQeCNyOlOLi7W7JvAmiJ9tJlkj40JDY79Hdx3NpdwGJ9U57Twup+TSHpf9XdMAv7cH4JnOXc8XUkSVjnwcH+ggSslofVdfe+wC+DxHOKgDonjnyuxDWBO4Jtpdl0jveo/dg1hYIQw3H6DskQgM8T2bbdDnHTFnzUkivdUSQkMFIU8frUvYqxLGS/PYinvcBRvb+AuucmDQvRIibsD5Hi3KqqYlceXJbozkzEPlS25UCt9pHsVFbhEhJ4/+WAla8RO3znjR8oitzRQxWcwGBApLTZJQJKSJOF++SopA2KM3lmkYJzxFvYIZpAdLtfFfOp403ydHmaEcCQSiDKUmCbBMQQHQNW7ndisEkTQw4XaD3N0QV0lymOIPhQVB/AL9i2tUFekqxke81mlfptsi6wEqx0VJPlZ8/O/q7b9iFjmW47oaMDr5TyRKeX57Zhp2IH7bQE6d6SK4iUuFvgmAHwDMVqppuAM+v8mZ7AQmU2ERff0ueOu7AkmcAMmkuNAtquyLON8WqLM8rYi4NXjESy4LDGw+MmQ54E6b1FU3P1ciO+A7xpu6U2rr4kbN2PzKRFhwCjyaNwFbE9TR4H4kYXJCYL8xqqoI=
    - secure: MFfigCYgOlmlP87+VW1YenKDUt6N+ODrd29wV/OeTI3WgWcwhzso8f/brVcNfUws0I8Qdzs3mEDbVL7HrpXkgSmlIk2Nir5gn0tkxjeAGFPr6YtE2BCSE8NcSyITNOurmJTeeva8I+m9zo/6eJP0ZkSJ2hsnjgLZG1UD8kzQ/mgHiNVG8o1i+mlO8jgcm8uhj0MLKY+sEeRinfze9pZKxS3DzqlXj/K/Te64rpA6q5PU3mFwnPGHzrZGoeRi8QIA4dNcQMn8HDgQI/KbyaMzULlFQYRU/C+pYB/eM+k0iKeXdHK6vil1SuyPrHLg4EuErSQuqEnAvfIsiY4qvN8kkZ90P49p0UlIHJsl6EbocOVll+WXxzPW5lamX/gLkWf0rks0yWO4SePSeDTV7HXl2cFwMa60fD8QOtVoqOtrarI9mbJ09JsviejKRGoXa5PKVf7cvP8WgOEGHKV+c90kdAvWu9up2Y9Sq0bXqpNsdsiunNKfTsW1hS8TkhYNisUv0F51maIirTQTQYI/jBI9w1ck9prHe7JuVHaIKyxAsThFuzb+3I2kaNQmDQ3TuIdleGW+E92YpwRKBhjbzZyXYtK2Ra3de5JHVUf+YatzDCa9MupnrLNzVSFBE1g5DXoj66hEcrpf/AFlxDLPcVY0r676mUYUt75p1JiHasT4CAM=

services:
  - docker

addons:
  apt:
    update: true

before_install:
  - cd jenkins
  - make jocker

before_script:
  - cd ..
  - make pull-base

script:
  - make build

after_success:
  - make jocker-ready
  - make agents
  - make test || travis_terminate 1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then make release; fi
