---
jenkins:
  nodes:
    ########
    # Deploy
    ########
    - permanent:
        name: "golang-1"
        labelString: "golang"
        nodeName: "golang-1"
        remoteFS: "/home/jenkins"
        numExecutors: 2
        launcher:
          jnlp:
            workDirSettings:
              failIfWorkDirIsMissing: false
    - permanent:
        name: "pulumi-1"
        labelString: "pulumi"
        nodeName: "pulumi-1"
        remoteFS: "/home/jenkins"
        numExecutors: 2
        launcher:
          jnlp:
            workDirSettings:
              failIfWorkDirIsMissing: false
    - permanent:
        name: "packer-1"
        labelString: "packer"
        nodeName: "packer-1"
        remoteFS: "/home/jenkins"
        numExecutors: 2
        launcher:
          jnlp:
            workDirSettings:
              failIfWorkDirIsMissing: false
    - permanent:
        name: "maven-1"
        labelString: "maven"
        nodeName: "maven-1"
        remoteFS: "/home/jenkins"
        numExecutors: 2
        launcher:
          jnlp:
            workDirSettings:
              failIfWorkDirIsMissing: false
